on:
  push:
    branches:
      -  'master'

#env:
 # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            persist-credentials: false
        
      
        
        - name: Update Kubernetes resources   
          run: |
            echo 'Add value19' >> springapp.yml
            
        
              
        - name: Commit files
          run: |
            #git config --local user.email "ike.lovelyn@yahoo.com"
            git config --local user.name "kiki023"
            git commit -am "Bump docker tag"
        
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.PAT }}
            branch: ${{ github.ref }}
