on:
  push:
    branches:
      -  'master'

env:
  GH_TOKEN: ${{ secrets.PAT }}   
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            ref: main
            token: ${{ secrets.PAT }}
          
      
        
        - name: Update Kubernetes resources   
          run: |
            echo 'Add value7' >> springapp.yml
       
        - name: Commit files
          run: |
            git config --local user.email "ike.lovelyn@yahoo.com"
            git config --local user.name "kiki023"
            git commit -am "Bump docker tag"
            git push
        #- name: Pushing to the protected branch 'protected'
        #  uses: CasperWA/push-protected@v2
       #   with:
       #     token: ${{ secrets.PAT }}
       #     branch: master
