on:
  push:
    branches:
      -  'master'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Update Kubernetes resources   
          run: |
            echo 'Add value3' >> springapp.yml
        - name: move to dir # Move the generated files into output folder
          run: |
            mkdir -p output
            yes| cp -rf springapp.yml ./output/
        - name: Commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Bump docker tag"
        
        - name: create pull request
          id: open-pr
          uses: repo-sync/pull-request@v2
          with:
            github_token: ${{ secrets.PAT }}
            destination_branch: master
            pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
            pr_body: "Automated Pull Request"
            pr_reviewer: "kiki023"
            pr_assignee: "kiki023"
            
        - name: Automatic Approve
          uses: mheap/automatic-approve-action@v1
          with:
            token: ${{ secrets.PAT }}
            workflows: "test.yml"
            dangerous_files: "aws.yml"

      # https://github.com/marketplace/actions/enable-pull-request-automerge
        - name: enable automerge
          if: steps.open-pr.outputs.pr_number != ''
          uses: peter-evans/enable-pull-request-automerge@v2
          with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
            merge-method: merge

          
            

