on:
  push:
    branches:
      -  'master'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Update Kubernetes resources   
          run: |
            echo 'Add value4' >> springapp.yml
       # - name: move to dir # Move the generated files into output folder
       #   run: |
       #     mkdir -p output
       #     yes| cp -rf springapp.yml ./output/
        - name: Commit files
          run: |
            git config --local user.email "ike.lovelyn@yahoo.com"
            git config --local user.name "kiki023"
            git commit -am "Bump docker tag"
        
        - name: Pushing to the protected branch 'protected'
          uses: CasperWA/push-protected@v2
          with:
            token: ${{ secrets.PAT }}
            branch: master
